"""create log table

Revision ID: 92eea971a5e6
Revises: 9d463a3037e1
Create Date: 2023-02-07 14:24:23.920953

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '92eea971a5e6'
down_revision = '9d463a3037e1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('access_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('ip_address', sa.String(length=255), nullable=False),
    sa.Column('user_agent', sa.String(length=255), nullable=False),
    sa.Column('method', sa.String(length=255), nullable=False),
    sa.Column('path', sa.String(length=255), nullable=False),
    sa.Column('status_code', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('wiki_access_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('site_name', sa.String(length=50), nullable=False),
    sa.Column('path', sa.String(length=255), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('user_unix_name', sa.String(length=255), nullable=False),
    sa.Column('ip_address', sa.String(length=255), nullable=True),
    sa.Column('user_agent', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('wiki_access_log')
    op.drop_table('access_log')
    # ### end Alembic commands ###
